package com.bots.crew.pp.webhook;

public enum MessagerUserStatus {
    GETTING_STARTED,
    SELECT_METHOD_OF_FINDING_MOVIE,
    SELECT_GENRE,
    SELECT_MOVIE_FROM_GENRE,
    SELECT_CINEMA,
    RQUEST_TO_SEND_LOCATION,
    SELECT_NUMBER_OF_TICKETS,
    SELECT_TECHNOLOGY,
    SELECT_TIME,

}
