package com.bots.crew.pp.webhook;

public enum MessangerUserStatus {
    GETTING_STARTED,
    SELECT_METHOD_OF_FINDING_MOVIE,
    SELECT_GENRE,
    SELECT_TODAY_MOVIE,
    SELECT_GENRE_MOVIE,
    SELECT_SESSION_DATE,
    SELECT_CINEMA_QUICK_LIST,
    SELECT_NEAREST_CINEMA,
    RQUEST_TO_SEND_LOCATION,
    SELECT_NUMBER_OF_TICKETS,
    SELECT_TECHNOLOGY,
    SELECT_TIME,
    RESERVATION_SHOWN
}
