package com.bots.crew.pp.webhook;

public enum MessangerUserStatus {
    GETTING_STARTED,
    SELECT_LIST_OR_FIND,
    SELECT_GENRE,
    SHOW_MOVIES,
    SHOW_GENRE_MOVIES,
    SELECT_SESSION_DATE,
    SELECT_CINEMA_QUICK_LIST,
    SELECT_NEAREST_CINEMA,
    RQUEST_TO_SEND_LOCATION,
    SELECT_NUMBER_OF_TICKETS,
    SELECT_TECHNOLOGY,
    SELECT_TIME,
    SHOW_RESERVATIONS,
}
